import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Button } from "@/components/ui/button";
import { FileText, Eye, Download } from "lucide-react";

interface ReportHistoryItem {
  id: number;
  title: string;
  generatedBy: string;
  date: string;
  format: string;
  size: string;
}

interface ReportHistoryProps {
  history: ReportHistoryItem[];
  handleViewReport: (id: number) => void;
  handleExportReport: (id: number) => void;
}

export const ReportHistory = ({
  history,
  handleViewReport,
  handleExportReport
}: ReportHistoryProps) => {
  return (
    <Card>
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <FileText className="h-5 w-5" />
          Recent Report History
        </CardTitle>
        <CardDescription>
          Recently generated reports
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Report Title</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Date</TableHead>
              <TableHead>Format</TableHead>
              <TableHead>Size</TableHead>
              <TableHead className="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {history.map((report) => (
              <TableRow key={report.id}>
                <TableCell className="font-medium">{report.title}</TableCell>
                <TableCell>{report.generatedBy}</TableCell>
                <TableCell>{report.date}</TableCell>
                <TableCell>{report.format}</TableCell>
                <TableCell>{report.size}</TableCell>
                <TableCell className="text-right">
                  <Button 
                    size="sm" 
                    variant="outline" 
                    className="mr-2"
                    onClick={() => handleViewReport(report.id)}
                  >
                    <Eye className="h-4 w-4" />
                  </Button>
                  <Button 
                    size="sm"
                    onClick={() => handleExportReport(report.id)}
                  >
                    <Download className="h-4 w-4" />
                  </Button>
                </TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
};
